language: java
jdk:
  - oraclejdk8
install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn clean cobertura:cobertura coveralls:report
after_success:
  - mvn converalls:report
